import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildEvidencePlan } from '../public/evidence-plan.js';
import { classifyBoundedCheckEvidence, classifyEvidencePlan } from '../public/evidence-plan-outcomes.js';

const check = { id: 'approval-binding', title: 'Verify exact-action approval binding', caseId: 'RT-PI-008' };
function run({ id='rtr_1', outcome='passed', roe='roe_1', fingerprint='a'.repeat(64), completed='2026-09-03T12:00:00.000Z', policy='policy-1', targetOrigin='https://test.example.com', mode='staging-adapter', signature=true, evidenceClass='customer-operated-controlled-adversarial-test' } = {}) { return { id, assessmentId:'asm_1', authorisationId:roe, signatureValid:signature, policyVersion:policy, createdAt:completed, trust:{evidenceClass}, campaign:{completedAt:completed,environment:'staging',target:{mode,endpointOrigin:targetOrigin,endpointPathHash:'b'.repeat(64),profile:null}}, results:[{caseId:'RT-PI-008',title:'Refund approval binding',severity:'critical',outcome,requestFingerprint:fingerprint,confidence:'high'}] }; }

test('simulation and invalid-signature runs are ignored as target evidence',()=>{const r=classifyBoundedCheckEvidence(check,[run({mode:'simulation'}),run({id:'rtr_2',signature:false})]);assert.equal(r.state,'open');assert.equal(r.finding,false);});
test('authorised failed adapter case becomes a confirmed evidence-backed failure',()=>{const r=classifyBoundedCheckEvidence(check,[run({outcome:'failed'})]);assert.equal(r.state,'confirmed-failure');assert.equal(r.finding,true);assert.equal(r.verified,false);});
test('inconclusive result never becomes a finding',()=>{const r=classifyBoundedCheckEvidence(check,[run({outcome:'inconclusive'})]);assert.equal(r.state,'inconclusive');assert.equal(r.finding,false);assert.equal(r.verified,false);});
test('passing probe without a reproduced failed baseline is supporting evidence only',()=>{const r=classifyBoundedCheckEvidence(check,[run()]);assert.equal(r.state,'supporting-pass');assert.equal(r.verified,false);});
test('exact retest requires same ROE, target, policy, fingerprint and chronology',()=>{const b=run({id:'rtr_base',outcome:'failed',completed:'2026-09-03T10:00:00.000Z'}),r=run({id:'rtr_retest',completed:'2026-09-03T11:00:00.000Z'}),o=classifyBoundedCheckEvidence(check,[r,b]);assert.equal(o.state,'exact-retest-supported');assert.equal(o.baselineRun.id,'rtr_base');assert.equal(o.latestRun.id,'rtr_retest');assert.equal(o.verified,false);});
test('changed fingerprint, ROE, target or policy does not qualify as exact retest',()=>{const b=run({id:'rtr_base',outcome:'failed',completed:'2026-09-03T10:00:00.000Z'});for(const r of [run({id:'fp',completed:'2026-09-03T11:00:00.000Z',fingerprint:'c'.repeat(64)}),run({id:'roe',completed:'2026-09-03T11:00:00.000Z',roe:'roe_2'}),run({id:'target',completed:'2026-09-03T11:00:00.000Z',targetOrigin:'https://other.example.com'}),run({id:'policy',completed:'2026-09-03T11:00:00.000Z',policy:'policy-2'})])assert.equal(classifyBoundedCheckEvidence(check,[r,b]).state,'supporting-pass');});
test('evidence plan never converts bounded evidence into automatic deployment approval',()=>{const b=run({id:'b',outcome:'failed',completed:'2026-09-03T10:00:00.000Z'}),r=run({id:'r',completed:'2026-09-03T11:00:00.000Z'}),o=classifyEvidencePlan({checks:[check],manual:[]},[r,b]);assert.equal(o.completeForProceed,false);assert.match(o.limitation,/does not infer.*deployment approval/i);});

test('not-applicable resolution removes only the mapped runtime question and is not a pass',()=>{
  const gap={id:'memory tenant isolation',title:'How is memory isolated and protected?',status:'evidence-required'};
  const assessment={result:{blockingEvidenceGaps:[gap],evidencePlanResolutions:{'memory-isolation':{state:'not-applicable',rationale:'No persistent agent or conversation memory boundary exists in the inspected target.',recordedAt:'2026-09-04T07:00:00.000Z'}}}};
  const plan=buildEvidencePlan({assessment,inspections:[{id:'ins_1'}]});
  assert.equal(plan.checks.length,0);assert.equal(plan.resolved.length,1);assert.equal(plan.resolved[0].resolution.state,'not-applicable');assert.equal(plan.state,'no-runtime-check-selected');
});

test('not-applicable action requires rationale and calls a persisted assessment endpoint',()=>{const source=fs.readFileSync(new URL('../public/inspector-evidence-plan.js',import.meta.url),'utf8');assert.match(source,/Mark not applicable/);assert.match(source,/rationale\.trim\(\)\.length<20/);assert.match(source,/evidence-plan\/resolutions/);assert.match(source,/not a PASS or verified control/i);});
test('production start preloads the authenticated evidence-plan resolution endpoint',()=>{const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));assert.match(pkg.scripts.start,/evidence-plan-resolution-preload/);const source=fs.readFileSync(new URL('../src/evidence-plan-resolution-preload.js',import.meta.url),'utf8');assert.match(source,/getUserFromRequest/);assert.match(source,/verifyCsrf/);assert.match(source,/evidencePlanResolutions/);assert.match(source,/reviewerUserId/);assert.match(source,/evidence_plan_not_applicable_recorded/);});

test('Inspector hydrates full Red Team runs before classification',()=>{const s=fs.readFileSync(new URL('../public/inspector-evidence-outcomes.js',import.meta.url),'utf8');assert.match(s,/\/api\/redteam\/runs\/\$\{encodeURIComponent\(summary\.id\)\}/);assert.match(s,/classifyEvidencePlan\(plan, fullRuns\)/);});
test('confirmed Red Team remediation is explicitly evidence-backed but not verified by assignment',()=>{const s=fs.readFileSync(new URL('../public/redteam-remediation-gate.js',import.meta.url),'utf8');assert.match(s,/source === 'redteam'/);assert.match(s,/Creating this remediation records ownership only\. It does not claim the fix is implemented or verified\./);assert.match(s,/item\.outcome === 'failed'/);});
test('result journey never auto-records Proceed from a passing test',()=>{const s=fs.readFileSync(new URL('../public/result-evidence-journey.js',import.meta.url),'utf8');assert.match(s,/accountable human must still review the full evidence chain/i);assert.match(s,/does not automatically record Proceed/i);assert.doesNotMatch(s,/decision:\s*['"]proceed['"]/i);});
test('exact retest context locks the original active Rules of Engagement or blocks',()=>{const s=fs.readFileSync(new URL('../public/redteam-evidence-context.js',import.meta.url),'utf8');assert.match(s,/select\.disabled = true/);assert.match(s,/Exact retest lineage cannot be preserved by silently creating a new authorisation/);assert.match(s,/create\.disabled = true/);});
