import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildEvidencePlan } from '../public/evidence-plan.js';
import { classifyBoundedCheckEvidence, classifyEvidencePlan } from '../public/evidence-plan-outcomes.js';
const check={id:'approval-binding',title:'Verify exact-action approval binding',caseId:'RT-PI-008'};
function run({id='rtr_1',outcome='passed',roe='roe_1',fingerprint='a'.repeat(64),completed='2026-09-03T12:00:00.000Z',policy='policy-1',targetOrigin='https://test.example.com',mode='staging-adapter',signature=true,evidenceClass='customer-operated-controlled-adversarial-test'}={}){return{id,assessmentId:'asm_1',authorisationId:roe,signatureValid:signature,policyVersion:policy,createdAt:completed,trust:{evidenceClass},campaign:{completedAt:completed,environment:'staging',target:{mode,endpointOrigin:targetOrigin,endpointPathHash:'b'.repeat(64),profile:null}},results:[{caseId:'RT-PI-008',title:'Refund approval binding',severity:'critical',outcome,requestFingerprint:fingerprint,confidence:'high'}]};}
test('simulation and invalid-signature runs are ignored as target evidence',()=>{const r=classifyBoundedCheckEvidence(check,[run({mode:'simulation'}),run({id:'rtr_2',signature:false})]);assert.equal(r.state,'open');assert.equal(r.finding,false);});
test('authorised failed adapter case becomes a confirmed evidence-backed failure',()=>{const r=classifyBoundedCheckEvidence(check,[run({outcome:'failed'})]);assert.equal(r.state,'confirmed-failure');assert.equal(r.finding,true);assert.equal(r.verified,false);});
test('inconclusive result never becomes a finding',()=>{const r=classifyBoundedCheckEvidence(check,[run({outcome:'inconclusive'})]);assert.equal(r.state,'inconclusive');assert.equal(r.finding,false);assert.equal(r.verified,false);});
test('passing probe without a reproduced failed baseline is supporting evidence only',()=>{const r=classifyBoundedCheckEvidence(check,[run()]);assert.equal(r.state,'supporting-pass');assert.equal(r.verified,false);});
test('exact retest requires same ROE, target, policy, fingerprint and chronology',()=>{const b=run({id:'rtr_base',outcome:'failed',completed:'2026-09-03T10:00:00.000Z'}),r=run({id:'rtr_retest',completed:'2026-09-03T11:00:00.000Z'}),o=classifyBoundedCheckEvidence(check,[r,b]);assert.equal(o.state,'exact-retest-supported');assert.equal(o.verified,false);});
test('evidence plan never converts bounded evidence into automatic deployment approval',()=>{const o=classifyEvidencePlan({checks:[check],manual:[]},[run()]);assert.equal(o.completeForProceed,false);assert.match(o.limitation,/deployment approval/i);});
test('not-applicable resolution removes mapped question without pass',()=>{const gap={id:'memory tenant isolation',status:'evidence-required'};const assessment={result:{blockingEvidenceGaps:[gap],evidencePlanResolutions:{'memory-isolation':{state:'not-applicable',rationale:'No persistent agent memory boundary exists in the inspected target.'}}}};const plan=buildEvidencePlan({assessment,inspections:[{id:'ins'}]});assert.equal(plan.checks.length,0);assert.equal(plan.resolved[0].resolution.state,'not-applicable');});
test('evidence-gap disposition removes selected runtime action but remains evidence needed',()=>{const gap={id:'outbound network egress',status:'evidence-required'};const assessment={result:{blockingEvidenceGaps:[gap],evidencePlanResolutions:{'egress-boundary':{state:'evidence-gap',rationale:'Source shows a network control but target runtime verification could not be completed.'}}}};const plan=buildEvidencePlan({assessment,inspections:[{id:'ins'}]});assert.equal(plan.checks.length,0);assert.equal(plan.resolved.length,1);assert.equal(plan.resolved[0].resolution.state,'evidence-gap');assert.equal(plan.state,'no-runtime-check-selected');});
test('Inspector offers persisted evidence-gap and not-applicable actions',()=>{const s=fs.readFileSync(new URL('../public/inspector-evidence-plan.js',import.meta.url),'utf8');assert.match(s,/Record evidence gap/);assert.match(s,/Mark not applicable/);assert.match(s,/state:isGap\?'evidence-gap':'not-applicable'/);assert.match(s,/not a PASS, verified control, confirmed finding or deployment approval/i);});
test('preload persists authenticated evidence dispositions',()=>{const s=fs.readFileSync(new URL('../src/evidence-plan-resolution-preload.js',import.meta.url),'utf8');assert.match(s,/getUserFromRequest/);assert.match(s,/verifyCsrf/);assert.match(s,/evidence-gap/);assert.match(s,/evidence_plan_gap_recorded/);assert.match(s,/reviewerUserId/);});
test('Inspector hydrates full Red Team runs before classification',()=>{const s=fs.readFileSync(new URL('../public/inspector-evidence-outcomes.js',import.meta.url),'utf8');assert.match(s,/classifyEvidencePlan\(plan, fullRuns\)/);});
test('result journey never auto-records Proceed from a passing test',()=>{const s=fs.readFileSync(new URL('../public/result-evidence-journey.js',import.meta.url),'utf8');assert.match(s,/it is never inferred from a scan or test result/i);assert.match(s,/data-deployment-decision="proceed"/);assert.match(s,/proceedBlocked/);});
