-- ARL-RKA-1.2 semantic correction for ARL-KB-011.
-- Created after human semantic review on 2026-10-01.
-- Previously applied migrations remain immutable.
-- Validation/lifecycle history is intentionally preserved.


UPDATE risk_knowledge_entries SET knowledge_version='ARL-RKA-1.2.0', problem_json='{"statement":"Unknown agents, models, prompts, tools or data stores escape assessment, patching and ownership.","customer_symptom":"Operators cannot demonstrate that every in-scope agent, model, prompt, tool, data store, service identity, deployment or scheduled AI component is represented in the current inventory with accountable ownership and lifecycle information.","credible_failure_or_attack":"Configuration drift, shadow AI adoption, undocumented experimentation, deployment changes or incomplete discovery can leave active AI assets outside the authoritative inventory, allowing them to escape assessment, patching, ownership and change control.","affected_assets":["agents and orchestration components","models, model endpoints and model configurations","system prompts and material prompt configurations","tools, MCP servers and external integrations","memory, vector stores and other AI data stores","service identities, scheduled jobs and deployments"],"default_severity":"high","severity_rationale":"Default high rating reflects the potential impact before customer-specific exposure, likelihood, reversibility and compensating controls are verified.","applicability":["all assessed AI systems"],"threat_actor_or_failure_source":"configuration drift, shadow AI adoption, incomplete discovery, undocumented experimentation or unmanaged deployment change","trust_boundary":"The control reconciles the declared authoritative inventory with assets actually observable inside the assessed scope and version.","operational_impact":"Undocumented or stale AI assets can remain unowned, unassessed, unpatched or outside approved lifecycle and change-control processes, preventing a defensible assessment of the deployed system."}', review_json='{"human_review_required":true,"last_reviewed":"2026-08-05","next_review_due":"2026-11-03","change_triggers":["ARL-KB-011 inventory schema, discovery source or reconciliation method change","ARL-KB-011 new agent, model, prompt, tool, data-store, provider or deployment type","ARL-KB-011 discovery of an undeclared, stale or ownerless asset","ARL-KB-011 evidence expiry or material assessment-scope change"],"review_status":"expert-authored candidate; customer and independent practitioner validation required"}', content_digest='5f32d0bfb97e50ca2d78f9eef7dc05c6e15f724e141ae0f7f9c7edec16e13ec4', updated_at='2026-08-06' WHERE id='ARL-KB-011';
UPDATE risk_knowledge_checks SET objective='Determine whether all in-scope AI assets and agentic components are completely, accurately and accountably represented in the current inventory.', method='Enumerate observable repositories, deployments, agents, model endpoints, prompt configurations, MCP servers, tools, data stores, service identities and scheduled jobs; reconcile them with the authoritative declared inventory. Verify each required inventory record has an accountable owner, purpose, environment, version or identifier, relevant data or permission scope, dependencies and lifecycle status. Record undeclared observed assets, stale declared assets and unresolved ownership or version gaps.', check_types_json='["declared-control review","observed-control inspection","inventory reconciliation","evidence review"]', required_evidence_json='["ARL-KB-011 assessed system, exact version, environment and inventory scope","The authoritative declared inventory or register used for the assessed version","Read-only discovery evidence identifying observable agents, models, prompts, tools, data stores, service identities, deployments and scheduled jobs in scope","A reproducible reconciliation showing matched, undeclared, stale, orphaned or unresolved inventory entries","Reviewer identity, timestamp and evidence digest binding the reconciliation to the assessed version"]', pass_condition='ARL-KB-011 passes only when every in-scope asset observed through the documented discovery sources is represented in the current authoritative inventory, required ownership and lifecycle metadata is present, no unresolved undeclared or stale asset remains, and the reconciliation evidence is attributable, reproducible and bound to the assessed version.', fail_condition='ARL-KB-011 fails when an in-scope observed AI asset or agentic component is absent from the authoritative inventory, a declared asset cannot be reconciled to the assessed system, required ownership or lifecycle information is missing, or the inventory reconciliation cannot be reproduced from version-bound evidence.', limitations='A bounded inventory reconciliation cannot prove the absence of dormant, externally hosted, transient or otherwise undiscoverable assets outside the stated discovery sources and assessment scope.', content_digest='e134377427e66f43a9ead67aa7eaac8b735bf51b6b8c67c8693e5a17d8e7769e', updated_at='2026-08-06' WHERE entry_id='ARL-KB-011';
UPDATE risk_knowledge_solutions SET control_objective='Reduce the likelihood and impact of ai assets and agents are not fully inventoried and make the remaining risk visible.', recommended_remediation='Maintain a continuously reconciled inventory with owner, purpose, environment, version, data class, permissions, dependencies and lifecycle status.', default_owner='Platform security owner', priority='P1', implementation_principles_json='["ARL-KB-011: maintain one authoritative, versioned inventory for in-scope AI assets and agentic components.","ARL-KB-011: reconcile inventory records against deterministic discovery sources and investigate every unresolved mismatch.","ARL-KB-011: require accountable ownership and lifecycle metadata before a new asset is accepted into the approved operating scope."]', monitoring='Monitor for differences between declared inventory and observable repositories, deployments, model endpoints, MCP/tool configuration and data stores; alert the Platform security owner on undeclared assets, stale records, missing owners and unexpected inventory drift.', containment='Restrict or hold an unregistered or materially unresolved AI asset from approved use until its identity, owner, purpose, scope, version, dependencies and lifecycle status are established and reviewed.', retest_acceptance_json='["ARL-KB-011: The exact remediated version has been reconciled against the authoritative inventory.","ARL-KB-011: No unresolved observed-but-undeclared, stale, orphaned or materially incomplete inventory entries remain.","ARL-KB-011: Required ownership, purpose, environment, version or identifier, dependencies and lifecycle information are recorded for in-scope assets.","ARL-KB-011: Reviewer identity, timestamp, assessed version, inventory version and evidence digest are recorded."]', content_digest='bee5ae5ddbafd1e6c06113e6801d522431d3430e123e0e80d52df60dfb1acb93', updated_at='2026-08-06' WHERE entry_id='ARL-KB-011';
UPDATE risk_knowledge_operational_metadata SET automation_status='candidate', customer_validation_status='unvalidated', content_digest='60e258f004b4c2b10b7a3a56b0e926b37ab04c9bdd6317b4d0113a49d40e1467', updated_at='2026-08-06' WHERE entry_id='ARL-KB-011';

DELETE FROM risk_knowledge_applicability_rules
WHERE entry_id='ARL-KB-011';

INSERT INTO risk_knowledge_applicability_rules
(id,entry_id,clause_index,predicate_index,source_label,clause_match,fact_key,operator,expected_value_json,derivation_status,unknown_behavior,created_at,updated_at)
VALUES
('ARL-KB-011-APP-01-01','ARL-KB-011',0,0,'all assessed AI systems','all','always','eq','true','derived_from_existing_label','include_for_review','2026-10-01','2026-10-01');
