-- ARL-RKA-1.2 semantic correction for ARL-KB-013.
-- Created after human semantic review on 2026-10-03.
-- Previously applied migrations remain immutable.
-- Applicability is intentionally unchanged.
-- Removes the weak informative OWASP API Security API7 SSRF mapping.

UPDATE risk_knowledge_entries SET knowledge_version='ARL-RKA-1.2.0', problem_json='{"statement":"The agent can send data to domains, webhooks or tools that are absent from the threat model.","customer_symptom":"An operator cannot account for every external domain, IP, webhook, tool endpoint, callback or proxy route the assessed agent can reach, creating an unreviewed path for data disclosure, unintended external interaction or policy bypass.","credible_failure_or_attack":"Untrusted input, unsafe agent behaviour, configuration drift or a compromised tool can cause the agent to use an external destination or egress route that was not included in the assessed architecture or approved destination inventory.","affected_assets":["outbound network paths and egress controls","external domains, IP addresses, webhooks and callbacks","tool endpoints and downstream services","data transmitted outside the assessed trust boundary","DNS, proxy and destination-routing configuration"],"default_severity":"high","severity_rationale":"Unknown or uncontrolled egress can enable data disclosure or unintended interaction with external systems. Final severity depends on reachable destinations, transmitted data, available actions, exposure, reversibility and compensating controls.","applicability":["network-capable agents"],"threat_actor_or_failure_source":"untrusted input, unsafe agent behaviour, compromised tool or dependency, configuration drift, or operator error","trust_boundary":"The boundary between the assessed agent or tool runtime and external network destinations, downstream services, webhooks, callbacks and other outbound routes.","operational_impact":"An undocumented or uncontrolled outbound path can expose scoped data, reach an unapproved service or bypass expected network controls. Operators may need to disable the route, investigate transmitted data and destinations, update the architecture inventory and repeat testing against the corrected version."}', review_json='{"human_review_required":true,"last_reviewed":"2026-10-03","next_review_due":"2026-12-02","change_triggers":["ARL-KB-013 destination inventory, egress policy, proxy, firewall or DNS enforcement change","ARL-KB-013 new or changed domain, IP, webhook, callback, tool endpoint, redirect or outbound route","ARL-KB-013 new dynamic-destination capability, egress bypass, route drift or incident evidence","ARL-KB-013 evidence expiry or material scope, architecture, environment or assessed-version change"],"review_status":"expert-authored candidate; customer and independent practitioner validation required"}', content_digest='aaef3a655fd6315c6488fe18ca0aebbaa541c2908f6d4202e41da01fe0b3e650', updated_at='2026-08-06' WHERE id='ARL-KB-013';
UPDATE risk_knowledge_checks SET objective='Determine whether all outbound destinations and egress paths available to the assessed agent are identified, attributable and constrained to the approved scope.', method='Compare declared architecture and network configuration with code, tool definitions and observed runtime DNS/HTTP activity. Enumerate domains, IP destinations, proxies, redirects, callbacks, webhooks and tool endpoints, including dynamically selected targets. In an owner-authorised non-production environment, attempt approved and unapproved destinations and verify enforcement occurs before external transmission.', check_types_json='["declared-control review","observed-control inspection","negative or abuse test","evidence review"]', required_evidence_json='["ARL-KB-013 assessed system, exact version, environment and network scope","Declared inventory of authorised external destinations, tools, webhooks, callbacks and egress routes","Relevant source, proxy, DNS, firewall, allowlist or tool configuration governing outbound access","Observed runtime DNS, HTTP, proxy, tool or network records for approved and attempted unapproved destinations","ARL-KB-013 tester identity, timestamp and evidence digest"]', pass_condition='ARL-KB-013 passes when the observed outbound destinations and routes match the documented authorised inventory, unapproved or unknown destinations are denied or explicitly routed to review before external transmission, and version-bound evidence shows the enforcement decision.', fail_condition='ARL-KB-013 fails when an outbound domain, IP, webhook, callback, tool endpoint or network route is reachable but absent from the assessed inventory or approved policy, or when an unapproved destination can be reached before the applicable egress control detects or blocks it.', limitations='This bounded ARL-KB-013 test does not prove absence of undiscovered paths, future regressions or risks outside the stated identities, inputs, environment and version.', content_digest='bb4a69d183808e4414084f8ac0f5256d49328d8437a8813d893d76d28cedd9e8', updated_at='2026-08-06' WHERE entry_id='ARL-KB-013';
UPDATE risk_knowledge_solutions SET control_objective='Maintain an attributable inventory of external destinations and enforce outbound network access so unknown or unapproved egress paths cannot silently operate.', recommended_remediation='Maintain an explicit destination and egress inventory; enforce deny-by-default outbound policy using controlled proxy, firewall or equivalent enforcement; apply destination allowlists and DNS/IP validation; constrain dynamic destinations; and record privacy-aware runtime egress evidence.', default_owner='Network security owner', priority='P0', implementation_principles_json='["ARL-KB-013: Maintain an authoritative inventory of approved external destinations and outbound routes for the assessed environment.","ARL-KB-013: Enforce deny-by-default egress outside the model using a controlled proxy, firewall or equivalent deterministic enforcement point.","ARL-KB-013: Resolve and validate destinations at execution time, record route and policy evidence, and fail closed when destination approval or enforcement state is unknown."]', monitoring='Record policy version and digest, actor or workload, resolved destination, route, decision and outcome; alert the Network security owner on unknown destinations, allowlist bypass attempts, route drift and missing egress evidence.', containment='Contain ARL-KB-013 by blocking or disabling the undocumented outbound route or destination, preserving relevant DNS, proxy, firewall, tool and runtime evidence, and requiring owner review before the route is re-enabled.', retest_acceptance_json='["ARL-KB-013: All observed external destinations and routes for the exact remediated version are represented in the approved inventory.","ARL-KB-013: Authorised in-scope destinations remain reachable through the documented egress path.","ARL-KB-013: Undeclared, unapproved and relevant dynamically redirected destinations are denied or held for explicit review before external transmission.","ARL-KB-013: Reviewer identity, timestamp, deployed version, evidence digest, known limitations and deployment decision are recorded."]', content_digest='aa29c25f10a95b744ab26a6d52d62a6e08fa3e1fa9890934ac866c92a0cea8bc', updated_at='2026-08-06' WHERE entry_id='ARL-KB-013';
UPDATE risk_knowledge_operational_metadata SET automation_status='candidate', customer_validation_status='unvalidated', content_digest='03a0ac78fdfe3eb2ca4bf3a704c7ea35b4b3defed3f46a5f427a6cac53d1435d', updated_at='2026-08-06' WHERE entry_id='ARL-KB-013';
INSERT INTO risk_knowledge_entry_classification (entry_id,default_severity,active_state,review_date,updated_at) VALUES ('ARL-KB-013','high','active','2026-10-03','2026-08-06') ON CONFLICT(entry_id) DO UPDATE SET default_severity=excluded.default_severity,active_state=excluded.active_state,review_date=excluded.review_date,updated_at=excluded.updated_at;

DELETE FROM risk_knowledge_mappings
WHERE entry_id='ARL-KB-013'
  AND reference_id='REF-OWASP-API-2023'
  AND framework_reference='API7 SSRF';
