-- Owner-approved KB-020 semantic correction. Additive: migrations 032 and earlier remain immutable.
-- Does not change assessments, applicability decisions, evidence, findings or deployment approvals.
-- Canonical values and SHA-256 digests are matched against risk-knowledge-v1.json.

UPDATE risk_knowledge_entries
SET problem_json='{"statement":"A stolen password can grant control over prompts, tools, policies, approvals or evidence.","customer_symptom":"A privileged administrator may obtain or recover high-impact access with a stolen password, a phishing-susceptible factor, weak recovery, or an unsafe enrolment or step-up fallback.","credible_failure_or_attack":"An attacker with a stolen password, compromised recovery channel or weaker-factor fallback can bypass phishing-resistant protection and gain privileged control of agent configuration, tool policy, approvals, deployment or assurance evidence.","affected_assets":["privileged administrator and break-glass identities","identity-provider authentication and recovery flows","MFA factor enrolment, reset and step-up controls","privileged sessions and administrative tool authority","agent policies, approvals, configuration and assurance evidence"],"default_severity":"high","severity_rationale":"Weak privileged authentication can allow takeover of high-impact administrative capabilities. Final severity depends on the authority of affected accounts, exposed functions, recovery controls and compensating safeguards.","applicability":["hosted platforms"],"threat_actor_or_failure_source":"credential phishing, password theft, factor downgrade, insecure recovery, privilege or session abuse, and misconfigured identity policy","trust_boundary":"The boundary between an untrusted or insufficiently authenticated caller and privileged administrative authority over the assessed system.","operational_impact":"If a stolen password can grant control over prompts, tools, policies, approvals or evidence, accountable operators may need to stop affected actions, investigate scoped data and identities, restore integrity, notify stakeholders where required, and hold deployment until retest evidence exists."}',
    review_json='{"human_review_required":true,"last_reviewed":"2026-10-09","next_review_due":"2026-12-02","change_triggers":["ARL-KB-020 privileged authentication, MFA, recovery, factor-enrolment or session-policy change","ARL-KB-020 new privileged role, administrative capability or high-impact operation","ARL-KB-020 phishing, account takeover, MFA bypass, insecure recovery or privileged-session incident","ARL-KB-020 evidence expiry or material scope, architecture or assessed-version change"],"review_status":"owner-approved semantic correction; independent practitioner and customer validation required"}',
    content_digest='3051c836ad9f77b3c2cd06bd6dcbe075bf4b0b0e02b6f5a638bb83f9995ab4a9',
    updated_at='2026-10-09'
WHERE id='ARL-KB-020';

UPDATE risk_knowledge_checks
SET objective='Determine whether every in-scope privileged account and access path enforces phishing-resistant authentication and whether enrolment, recovery, fallback, break-glass and privileged step-up prevent weaker authentication from gaining equivalent authority.',
    method='Identify the exact assessed version, environment, privileged roles, identity providers and administrative actions. Review the approved privileged authentication and recovery policy, the account inventory, MFA-factor enrolment and reset settings, step-up, session lifetime and break-glass controls. Inspect privacy-safe source and IdP configuration without collecting secret values. Under separate owner authorisation, perform bounded positive and negative tests with synthetic privileged accounts for login, weaker-factor fallback, recovery, factor reset and privileged step-up; retain attributable identity-provider or application events. Reconcile observed paths, exceptions and limitations with policy and record accountable human review.',
    required_evidence_json='["ARL-KB-020 exact assessed system version, environment, privileged-account and administrative-action scope","ARL-KB-020 organisation-approved privileged authentication policy for phishing-resistant MFA, enrolment, recovery, step-up and break-glass exceptions","ARL-KB-020 authoritative privileged-account inventory with roles, owners, identity providers and approved exceptions","ARL-KB-020 source or configuration evidence for IdP MFA policies, factor enrolment, recovery, session and privileged step-up settings","ARL-KB-020 bounded positive evidence of authorised phishing-resistant privileged login and step-up with observed authentication events","ARL-KB-020 bounded negative evidence of prohibited weaker-factor fallback, recovery bypass, factor reset, break-glass misuse and session bypass with denial events","ARL-KB-020 tester identity, reviewer identity, role, timestamp, assessed version and evidence digest"]',
    pass_condition='ARL-KB-020 passes only when accountable evidence for the exact assessed version identifies the privileged accounts and approved authentication policy; authorised login and step-up enforce phishing-resistant protection; prohibited weaker-factor, enrolment, recovery, break-glass and session bypass paths cannot grant the same authority; documented exceptions and limits receive explicit human review; and all required observed tests and authentication events are attributable.',
    fail_condition='ARL-KB-020 fails or requires review when a privileged account or access path permits password-only, phishing-susceptible or uncontrolled fallback authentication; when enrolment, recovery, factor reset, break-glass or step-up bypasses the required strength; or when policy, scoped inventory, source configuration, observed denial evidence or accountable review is absent or mismatched to the assessed version.',
    content_digest='4e422f2fb25d9d2bbe754488c2b50356910402ee32de76cf58e2ecf31cfdb606',
    updated_at='2026-10-09'
WHERE entry_id='ARL-KB-020';

UPDATE risk_knowledge_solutions
SET retest_acceptance_json='["ARL-KB-020: The exact remediated privileged authentication configuration, roles, approved factors and relevant identity-provider policy digest are recorded.","ARL-KB-020: Authorised synthetic privileged login and sensitive-action step-up work with a phishing-resistant factor and scoped authority.","ARL-KB-020: Password-only, downgrade, recovery, re-enrolment, break-glass and session bypass variants cannot obtain privileged authority; denial events are retained.","ARL-KB-020: Reviewer identity, assessed version, test scope, evidence digest, documented exceptions and human decision are recorded."]',
    content_digest='485677a3b4d2e0ff7aaebd124ffabebda48e060923af045a9371249a8e85e9f1',
    updated_at='2026-10-09'
WHERE entry_id='ARL-KB-020';
