from pathlib import Path

core = Path('src/control-intelligence-core.js')
text = core.read_text()
anchor = "async function deriveDeploymentDecision(access, snapshot) {\n"
helper = """async function verifiedClosedRemediationControlIds(access, snapshot, currentEvidence = []) {\n  const rows = await db.prepare(`SELECT rt.entry_id,rt.id retest_id,failed.id failed_id,r.id finding_id\n    FROM control_test_executions rt\n    JOIN control_test_executions failed ON failed.id=rt.retest_of_execution_id\n      AND failed.workspace_id=rt.workspace_id AND failed.project_id=rt.project_id AND failed.entry_id=rt.entry_id\n    JOIN remediation_items r ON r.id=rt.finding_id AND r.project_id=rt.project_id\n    JOIN control_finding_bindings b ON b.finding_id=r.id AND b.workspace_id=rt.workspace_id\n      AND b.project_id=rt.project_id AND b.entry_id=rt.entry_id AND b.system_snapshot_id=failed.system_snapshot_id\n    WHERE rt.workspace_id=? AND rt.project_id=? AND rt.system_snapshot_id=?\n      AND rt.execution_kind='retest' AND rt.result='passed'\n      AND rt.finding_id=failed.finding_id AND rt.remediation_id=rt.finding_id\n      AND rt.original_snapshot_id=failed.system_snapshot_id AND rt.original_snapshot_id<>rt.system_snapshot_id\n      AND failed.execution_kind='initial' AND failed.result='failed'\n      AND r.status='verified_closed'`)\n    .all(access.project.workspace_id,access.project.id,snapshot.id);\n  if (!rows.length) return new Set();\n  const evidenceByTest = new Set(currentEvidence.filter((row) => row.verification_state==='verified' && row.retention_status==='active').map((row) => row.test_execution_id));\n  const failedRows = await db.prepare(`SELECT * FROM control_test_executions WHERE workspace_id=? AND project_id=? AND id IN (${rows.map(()=>'?').join(',')})`)\n    .all(access.project.workspace_id,access.project.id,...rows.map((row)=>row.failed_id));\n  await verifyRows(failedRows,'content_digest','test');\n  return new Set(rows.filter((row) => evidenceByTest.has(row.retest_id)).map((row) => row.entry_id));\n}\n\n"""
if helper not in text:
    if anchor not in text: raise SystemExit('deriveDeploymentDecision anchor missing')
    text = text.replace(anchor, helper + anchor, 1)
old = """  const applicable = evaluations.filter((row) => row.applicability_status === 'applicable');\n  const unknown = evaluations.filter((row) => row.applicability_status === 'unknown');\n  const tested = new Set(tests.filter((row) => row.result === 'passed' && (row.execution_kind==='initial'||validRetest(row,tests,findings))).map((row) => row.entry_id));\n  const observed = new Set(evidence.filter((row) => ['verified'].includes(row.verification_state) && row.retention_status === 'active').map((row) => row.entry_id));\n  const missingEvidence = applicable.filter((row) => !tested.has(row.entry_id) || !observed.has(row.entry_id)).length;\n"""
new = """  const closedSatisfied = await verifiedClosedRemediationControlIds(access,snapshot,evidence);\n  const effectiveEvaluations = evaluations.map((row) => closedSatisfied.has(row.entry_id) && row.applicability_status==='unknown' ? { ...row, applicability_status: 'applicable' } : row);\n  const applicable = effectiveEvaluations.filter((row) => row.applicability_status === 'applicable');\n  const unknown = effectiveEvaluations.filter((row) => row.applicability_status === 'unknown');\n  const tested = new Set(tests.filter((row) => row.result === 'passed' && (row.execution_kind==='initial'||validRetest(row,tests,findings))).map((row) => row.entry_id));\n  for (const controlId of closedSatisfied) tested.add(controlId);\n  const observed = new Set(evidence.filter((row) => ['verified'].includes(row.verification_state) && row.retention_status === 'active').map((row) => row.entry_id));\n  const missingEvidence = applicable.filter((row) => !tested.has(row.entry_id) || !observed.has(row.entry_id)).length;\n"""
if old not in text: raise SystemExit('deployment applicability block missing')
text = text.replace(old, new, 1)
old_summary = "completedRetests: tests.filter((row) => validRetest(row,tests,findings)).length,requiredApprovals:requiredApprovals.length"
new_summary = "completedRetests: new Set([...tests.filter((row) => validRetest(row,tests,findings)).map((row)=>row.entry_id),...closedSatisfied]).size,requiredApprovals:requiredApprovals.length"
if old_summary not in text: raise SystemExit('completedRetests summary anchor missing')
text = text.replace(old_summary, new_summary, 1)
core.write_text(text)

test_file = Path('tests/control-intelligence-redteam-binding.test.js')
t = test_file.read_text()
if "async function lineage(f) {" not in t: raise SystemExit('lineage signature missing')
t = t.replace("async function lineage(f) {", "async function lineage(f, { reassessCurrent = true } = {}) {", 1)
old_current = "  const current = await applicableSnapshot(f, 'Synthetic remediated v2');"
new_current = """  const current = reassessCurrent\n    ? await applicableSnapshot(f, 'Synthetic remediated v2')\n    : (await createSystemSnapshot({ projectId: f.project.id, userId: f.userId, input: { architecture: { summary: 'Synthetic remediated v2' }, assessmentConfiguration: { architectureFacts: [FACT] }, source: 'test' } })).snapshot;"""
if old_current not in t: raise SystemExit('current snapshot line missing')
t = t.replace(old_current, new_current, 1)
append = """\n\ntest('deployment decision treats a verified-closed exact remediation lineage as satisfied without inventing a new applicability revision', async () => {\n  const f = await fixture('redteam-closed-lineage-decision');\n  const chain = await lineage(f, { reassessCurrent: false });\n  const raw = await db.prepare('SELECT applicability_status FROM control_snapshot_evaluations WHERE project_id=? AND system_snapshot_id=? AND entry_id=?').get(f.project.id, chain.current.id, CONTROL_ID);\n  assert.equal(raw.applicability_status, 'unknown');\n  const runs = await redTeamPair(f);\n  await bind(f, chain, runs);\n  const detail = await getControlIntelligenceControl({ projectId: f.project.id, controlId: CONTROL_ID, userId: f.userId });\n  const finding = detail.findings.find((item) => item.id === chain.finding.id);\n  await closeControlFinding({ projectId: f.project.id, controlId: CONTROL_ID, findingId: chain.finding.id, userId: f.userId, input: { systemSnapshotId: chain.current.id, expectedUpdatedAt: finding.updatedAt, limitations: 'Exact synthetic closure only.' } });\n  const decision = await recordDeploymentDecision({ projectId: f.project.id, userId: f.userId, input: { systemSnapshotId: chain.current.id } });\n  assert.equal(decision.decision, 'hold');\n  assert.equal(decision.summary.applicableControls, 1);\n  assert.equal(decision.summary.controlsMissingEvidence, 0);\n  assert.equal(decision.summary.completedRetests, 1);\n  assert.equal(decision.summary.controlsNeedingAssessment, 107);\n  assert.ok(decision.reasons.includes('material_context_missing'));\n  assert.ok(!decision.reasons.includes('required_evidence_missing'));\n});\n"""
if "deployment decision treats a verified-closed exact remediation lineage" not in t: t += append
test_file.write_text(t)
