const EVIDENCE = {
    none: { label: 'No evidence available', score: 0, multiplier: 1.18 },
    claimed: { label: 'Owner statement only', score: 35, multiplier: 1.08 },
    documented: { label: 'Documented policy or configuration', score: 70, multiplier: 1.0 },
    tested: { label: 'Tested evidence, logs or review record', score: 100, multiplier: 0.92 },
};
const option = (value, label, points, tags = []) => ({ value, label, points, tags });
export const questionnaire = [
    { id: 'business_impact', domain: 'Business impact', kind: 'exposure', title: 'What is the maximum credible business impact if the agent behaves incorrectly?', help: 'Consider customer harm, financial loss, operational interruption and legal exposure.', options: [option('minor', 'Minor inconvenience with easy recovery', 0), option('material', 'Material internal disruption or rework', 4, ['impact']), option('major', 'Customer harm, major loss or reportable incident', 7, ['impact', 'high-impact']), option('severe', 'Severe financial, legal, safety or systemic harm', 10, ['impact', 'high-impact', 'critical'])] },
    { id: 'data_sensitivity', domain: 'Data protection', kind: 'exposure', title: 'What is the most sensitive data the agent can access?', help: 'Classify the highest sensitivity level available to the agent.', options: [option('public', 'Public or synthetic data only', 0), option('internal', 'Internal business information', 4, ['data']), option('personal', 'Personal, customer or confidential data', 7, ['data', 'privacy']), option('regulated', 'Financial, health, legal, authentication or regulated data', 10, ['data', 'privacy', 'regulated'])] },
    { id: 'autonomy', domain: 'Autonomy', kind: 'exposure', title: 'How independently can the agent act?', help: 'Autonomous execution increases the blast radius of an unsafe decision.', options: [option('advice', 'It only recommends actions', 0), option('draft', 'It prepares drafts for approval', 3, ['approval']), option('limited', 'It performs limited actions automatically', 7, ['autonomy']), option('full', 'It plans and executes across systems autonomously', 10, ['autonomy', 'critical'])] },
    { id: 'transactions', domain: 'High-impact actions', kind: 'exposure', title: 'Can it move money, delete data, publish content or create binding commitments?', help: 'Include financial, legal, access-control and irreversible operational actions.', options: [option('none', 'No high-impact actions', 0), option('draft', 'It prepares them for human approval', 3, ['high-impact', 'approval']), option('bounded', 'It executes within enforced limits', 7, ['high-impact']), option('unbounded', 'It can execute with weak or no hard limits', 10, ['high-impact', 'critical'])] },
    { id: 'network_exposure', domain: 'Attack surface', kind: 'exposure', title: 'Who can reach the agent or influence its inputs?', help: 'Public and partner-facing systems face more adversarial input.', options: [option('private', 'Private, tightly controlled users and inputs', 0), option('workforce', 'Authenticated workforce users', 3, ['exposure']), option('partners', 'Partners, customers or broad user groups', 7, ['exposure']), option('public', 'Open public access or anonymous input', 10, ['exposure', 'critical'])] },
    { id: 'external_content', domain: 'Prompt injection', kind: 'exposure', title: 'Does it process untrusted documents, email, web pages or retrieved content?', help: 'Indirect prompt injection commonly enters through data that appears legitimate.', options: [option('none', 'No external or untrusted content', 0), option('curated', 'Only curated, trusted sources', 3, ['prompt-injection']), option('mixed', 'A mix of trusted and untrusted sources', 7, ['prompt-injection']), option('open', 'Open web, inboxes, uploads or arbitrary retrieval', 10, ['prompt-injection', 'critical'])] },
    { id: 'tool_scope', domain: 'Tool security', kind: 'exposure', title: 'What can connected tools or MCP servers do?', help: 'Focus on write access, command execution and access to sensitive systems.', options: [option('none', 'No tools, or read-only low-risk tools', 0), option('narrow', 'Small allowlist with narrow write actions', 3, ['tools']), option('broad', 'Multiple tools with broad business access', 7, ['tools', 'mcp']), option('privileged', 'Admin, shell, code execution or dynamic tool discovery', 10, ['tools', 'mcp', 'critical'])] },
    { id: 'multi_agent', domain: 'Agent relationships', kind: 'exposure', title: 'Can this agent delegate to or receive instructions from other agents?', help: 'Delegation chains can propagate untrusted instructions and authority.', options: [option('none', 'No multi-agent communication', 0), option('fixed', 'Fixed, authenticated agent relationships', 3, ['multi-agent']), option('several', 'Several agents with shared context or tools', 7, ['multi-agent']), option('dynamic', 'Dynamic delegation or untrusted agent discovery', 10, ['multi-agent', 'critical'])] },
    { id: 'permissions', domain: 'Identity and access', kind: 'control', title: 'How are agent permissions constrained?', help: 'Use a dedicated identity and grant only the operations required for the task.', options: [option('scoped', 'Dedicated identity with least privilege and explicit deny rules', 0), option('role', 'Dedicated role but permissions are broader than necessary', 4, ['permissions']), option('user', 'Shared user/service credentials or broad inherited access', 7, ['permissions']), option('admin', 'Administrator, owner or wildcard permissions', 10, ['permissions', 'critical'])] },
    { id: 'credentials', domain: 'Secrets', kind: 'control', title: 'How are credentials issued and protected?', help: 'Long-lived secrets increase persistence and lateral-movement risk.', options: [option('jit', 'Vaulted, short-lived, scoped and automatically rotated', 0), option('vault', 'Vaulted but long-lived or manually rotated', 3, ['secrets']), option('env', 'Static environment secrets shared across services', 7, ['secrets']), option('exposed', 'Secrets may appear in prompts, code, logs or memory', 10, ['secrets', 'critical'])] },
    { id: 'tool_authorization', domain: 'Tool security', kind: 'control', title: 'What independently authorises each tool action?', help: 'The model must not be the final authority for its own permissions.', options: [option('policy', 'Deterministic policy engine checks user, action, resource and context', 0), option('allowlist', 'Tool allowlist with basic parameter validation', 3, ['tools']), option('prompt', 'Prompt instructions are the main restriction', 7, ['tools']), option('none', 'No independent authorisation boundary', 10, ['tools', 'critical'])] },
    { id: 'human_approval', domain: 'Human oversight', kind: 'control', title: 'How are high-impact actions approved?', help: 'Approval must display the exact action, target, amount and consequence.', options: [option('bound', 'Transaction-bound approval for every high-impact action', 0), option('threshold', 'Enforced approval above clear thresholds', 3, ['approval']), option('informal', 'Informal or inconsistent review', 7, ['approval']), option('none', 'No human approval requirement', 10, ['approval', 'critical'])] },
    { id: 'input_boundary', domain: 'Prompt injection', kind: 'control', title: 'How is untrusted content separated from trusted instructions?', help: 'Retrieved content should be data, not executable authority.', options: [option('strong', 'Trusted/untrusted separation plus deterministic policy checks', 0), option('filtered', 'Filtering, delimiters and source labelling', 3, ['prompt-injection']), option('prompt-only', 'Prompt wording is the primary defence', 7, ['prompt-injection']), option('none', 'Untrusted content can directly influence actions', 10, ['prompt-injection', 'critical'])] },
    { id: 'output_validation', domain: 'Output safety', kind: 'control', title: 'How are model outputs validated before use?', help: 'Validate structure, destination, content and policy before execution.', options: [option('schema', 'Strict schema, business-rule and destination validation', 0), option('partial', 'Schema validation for some actions', 3, ['output']), option('manual', 'Ad hoc checks or manual review only', 7, ['output']), option('none', 'Outputs are executed or published directly', 10, ['output', 'critical'])] },
    { id: 'memory_security', domain: 'Memory and context', kind: 'control', title: 'How is memory isolated and protected?', help: 'Persistent memory can be poisoned or leak data across users and sessions.', options: [option('isolated', 'Per-tenant isolation, validation, provenance and retention limits', 0), option('segmented', 'Basic user/session separation and retention controls', 3, ['memory']), option('shared', 'Shared or weakly separated memory/context', 7, ['memory']), option('uncontrolled', 'Unvalidated persistent memory with sensitive data', 10, ['memory', 'critical'])] },
    { id: 'data_minimisation', domain: 'Data protection', kind: 'control', title: 'Is sensitive data minimised before model processing?', help: 'Only the minimum necessary data should enter prompts, memory and traces.', options: [option('strong', 'Classification, redaction, field-level minimisation and retention limits', 0), option('partial', 'Some redaction and retention controls', 3, ['data', 'privacy']), option('broad', 'Broad datasets are sent with limited minimisation', 7, ['data', 'privacy']), option('none', 'Sensitive data is copied freely into prompts, memory or logs', 10, ['data', 'privacy', 'critical'])] },
    { id: 'egress_control', domain: 'Network security', kind: 'control', title: 'How is outbound network access controlled?', help: 'Restrict destinations, protocols, payloads and download behaviour.', options: [option('deny', 'Default-deny egress with explicit destination allowlists', 0), option('proxy', 'Controlled proxy with monitoring and domain restrictions', 3, ['egress']), option('broad', 'Broad internet access with limited filtering', 7, ['egress']), option('open', 'Unrestricted outbound access or arbitrary downloads', 10, ['egress', 'critical'])] },
    { id: 'supply_chain', domain: 'Supply chain', kind: 'control', title: 'How are models, tools, packages and MCP servers governed?', help: 'Inventory, provenance, signing and version pinning reduce dependency risk.', options: [option('governed', 'Approved inventory, provenance checks, pinning and change review', 0), option('inventory', 'Inventory and partial version controls', 3, ['supply-chain']), option('informal', 'Informal review and floating versions', 7, ['supply-chain']), option('dynamic', 'Unreviewed or dynamically installed components', 10, ['supply-chain', 'critical'])] },
    { id: 'logging', domain: 'Observability', kind: 'control', title: 'Can you reconstruct what the agent saw, decided and changed?', help: 'Logs should link identity, input source, model decision, tool call, approval and side effect.', options: [option('complete', 'Tamper-resistant, correlated decision and action logs', 0), option('standard', 'Good application and tool logs but incomplete decision context', 3, ['monitoring']), option('partial', 'Partial logs with gaps in inputs, approvals or effects', 7, ['monitoring']), option('none', 'Little or no reliable audit trail', 10, ['monitoring', 'critical'])] },
    { id: 'detection', domain: 'Detection and response', kind: 'control', title: 'Are unsafe patterns detected in near real time?', help: 'Detect unusual tool chains, repeated denials, data exfiltration and runaway loops.', options: [option('active', 'Behaviour baselines, alerts and automated containment', 0), option('alerts', 'Rule-based alerts with an on-call response', 3, ['monitoring']), option('review', 'Periodic manual log review', 7, ['monitoring']), option('none', 'No agent-specific monitoring or alerting', 10, ['monitoring', 'critical'])] },
    { id: 'cost_limits', domain: 'Resource abuse', kind: 'control', title: 'Are token, retry, recursion and spend limits enforced outside the model?', help: 'Hard limits prevent denial-of-wallet and runaway execution.', options: [option('hard', 'Per-run, per-user and daily hard limits with circuit breakers', 0), option('some', 'Some caps and timeouts', 3, ['resource']), option('soft', 'Soft warnings or prompt-based limits', 7, ['resource']), option('none', 'Unlimited loops, retries, tool chains or spend', 10, ['resource', 'critical'])] },
    { id: 'testing', domain: 'Security assurance', kind: 'control', title: 'What adversarial testing blocks unsafe releases?', help: 'Test direct/indirect injection, tool misuse, leakage, memory poisoning and abuse cases.', options: [option('gated', 'Automated adversarial suite and release gates', 0), option('regular', 'Regular manual and automated testing without full gates', 3, ['testing']), option('occasional', 'Occasional testing after major changes', 7, ['testing']), option('none', 'No structured agent-security testing', 10, ['testing', 'critical'])] },
    { id: 'change_management', domain: 'Lifecycle governance', kind: 'control', title: 'What changes trigger security review and reassessment?', help: 'Models, prompts, tools, permissions, data sources and hosting can all change risk.', options: [option('gated', 'Material changes require review, tests and signed approval', 0), option('tracked', 'Changes are tracked with periodic reassessment', 3, ['governance']), option('informal', 'Reviews depend on individual judgement', 7, ['governance']), option('none', 'No defined security change gate', 10, ['governance', 'critical'])] },
    { id: 'kill_switch', domain: 'Incident response', kind: 'control', title: 'Can the agent be contained quickly and safely?', help: 'Containment should revoke credentials, stop queues and block tools without model cooperation.', options: [option('tested', 'One-step tested containment with credential revocation', 0), option('manual', 'Documented manual shutdown tested periodically', 3, ['incident-response']), option('slow', 'Several manual steps with unclear ownership', 7, ['incident-response']), option('none', 'No reliable emergency stop', 10, ['incident-response', 'critical'])] },
    { id: 'ownership', domain: 'Governance', kind: 'control', title: 'Is one accountable owner responsible for this agent?', help: 'The owner should accept risk, approve changes and coordinate incidents.', options: [option('clear', 'Named business and technical owners with documented duties', 0), option('single', 'A named owner but incomplete responsibilities', 3, ['governance']), option('shared', 'Shared or ambiguous ownership', 7, ['governance']), option('none', 'No accountable owner', 10, ['governance', 'critical'])] },
];
export const evidenceOptions = Object.entries(EVIDENCE).map(([value, item]) => ({ value, label: item.label }));
const guidance = {
    permissions: ['Create a dedicated non-human identity and remove inherited or wildcard permissions.', 'Enforce resource-level deny rules outside the model.'],
    secrets: ['Move all credentials to a managed vault and issue short-lived, task-scoped tokens.', 'Scan prompts, traces, memory and logs for secret leakage.'],
    tools: ['Put every tool call behind deterministic authorisation and parameter validation.', 'Maintain a reviewed tool allowlist and disable dynamic discovery in production.'],
    approval: ['Require transaction-bound approval for every high-impact action.', 'Show approvers the exact target, amount, data and irreversible consequence.'],
    'prompt-injection': ['Treat retrieved and user-supplied content as untrusted data, never authority.', 'Separate trusted instructions from content and enforce policy at the tool boundary.'],
    output: ['Require schema validation, destination checks and business-rule validation before execution.'],
    memory: ['Isolate memory by tenant and session; validate writes and retain provenance.', 'Add expiry, deletion and poisoning-detection controls.'],
    data: ['Minimise and redact sensitive fields before model processing.', 'Apply purpose limits, retention controls and access logging.'],
    privacy: ['Complete a privacy impact assessment and document processing purposes and retention.'],
    egress: ['Adopt default-deny network egress with explicit destinations and payload controls.'],
    'supply-chain': ['Inventory and pin models, packages, tools and MCP servers; verify provenance before release.'],
    monitoring: ['Correlate inputs, model decisions, tool calls, approvals and side effects.', 'Alert on denied actions, unusual tool sequences, exfiltration indicators and runaway loops.'],
    resource: ['Enforce hard token, time, recursion, retry and spend limits outside the model.'],
    testing: ['Add adversarial regression tests for injection, leakage, tool misuse, memory poisoning and unsafe delegation.', 'Block release when critical abuse cases fail.'],
    governance: ['Assign accountable business and technical owners and define reassessment triggers.'],
    'incident-response': ['Implement and exercise a one-step kill switch that revokes credentials and stops tool execution.'],
    critical: ['Do not deploy or expand this configuration until critical controls are independently verified.'],
};
const frameworks = {
    permissions: ['OWASP Agentic: Excessive Agency', 'NIST AI RMF MANAGE 2'], tools: ['OWASP Agentic: Tool Misuse', 'OWASP Agent Security - Tool Security'], approval: ['OWASP Agent Security - Human-in-the-Loop'], 'prompt-injection': ['OWASP LLM01 Prompt Injection', 'OWASP Agentic: Agent Goal Hijack'], memory: ['OWASP Agentic: Memory Poisoning'], data: ['NIST AI RMF MAP 2', 'NIST AI 600-1 Data Privacy'], monitoring: ['NIST AI RMF MEASURE 2', 'OWASP Agent Security - Monitoring'], testing: ['NIST AI RMF MEASURE 2.7', 'OWASP Secure Agent Testing'], 'supply-chain': ['OWASP LLM03 Supply Chain'], resource: ['OWASP LLM10 Unbounded Consumption'], 'incident-response': ['NIST AI RMF MANAGE 4'], governance: ['NIST AI RMF GOVERN'], egress: ['OWASP Agentic: Data Exfiltration'], secrets: ['OWASP Agent Security - Secrets'], output: ['OWASP LLM05 Improper Output Handling'], 'multi-agent': ['OWASP Agent Security - Multi-Agent Security']
};
function band(score) {
    if (score >= 75)
        return 'Critical';
    if (score >= 50)
        return 'High';
    if (score >= 25)
        return 'Moderate';
    return 'Low';
}
function severity(points) { return points >= 9 ? 'critical' : points >= 7 ? 'high' : points >= 4 ? 'medium' : 'low'; }
function normaliseAnswer(raw) { return typeof raw === 'string' ? { value: raw, evidence: 'claimed' } : { value: raw?.value, evidence: raw?.evidence || 'none' }; }
function uniq(items) { return [...new Set(items.filter(Boolean))]; }
function attackPaths(answers) {
    const val = (id) => normaliseAnswer(answers[id]).value;
    const paths = [];
    const add = (condition, title, narrative, severity, tags) => {
        if (condition)
            paths.push({ id: `AP-${String(paths.length + 1).padStart(2, '0')}`, title, narrative, severity, tags, frameworks: uniq(tags.flatMap(t => frameworks[t] || [])) });
    };
    add(['mixed', 'open'].includes(val('external_content')) && ['prompt-only', 'none'].includes(val('input_boundary')) && ['broad', 'privileged'].includes(val('tool_scope')), 'Indirect prompt injection to privileged tool execution', 'Untrusted content can influence an agent that has broad tool authority without a strong policy boundary. A malicious document, message or web page could redirect the agent into unauthorised actions.', 'critical', ['prompt-injection', 'tools']);
    add(['full', 'limited'].includes(val('autonomy')) && ['none', 'informal'].includes(val('human_approval')) && ['bounded', 'unbounded'].includes(val('transactions')), 'Autonomous high-impact action without transaction-bound approval', 'The agent can execute consequential actions while approval is absent or weak. A model error, compromised context or malicious instruction could become an immediate business event.', 'critical', ['approval', 'high-impact']);
    add(['admin', 'user'].includes(val('permissions')) && ['exposed', 'env'].includes(val('credentials')), 'Credential compromise with excessive blast radius', 'Broad privileges combined with static or exposed credentials create a durable path to lateral movement and high-impact system access.', 'critical', ['permissions', 'secrets']);
    add(['shared', 'uncontrolled'].includes(val('memory_security')) && ['personal', 'regulated'].includes(val('data_sensitivity')), 'Cross-user data leakage or persistent memory poisoning', 'Sensitive information is processed alongside weakly isolated persistent memory, increasing the chance of cross-session disclosure and long-lived malicious instructions.', 'high', ['memory', 'data']);
    add(['open', 'broad'].includes(val('egress_control')) && ['personal', 'regulated'].includes(val('data_sensitivity')), 'Sensitive-data exfiltration through outbound channels', 'The agent can access sensitive data and communicate broadly outbound, creating a direct route for accidental or adversarial exfiltration.', 'critical', ['egress', 'data']);
    add(['dynamic'].includes(val('supply_chain')) || ['dynamic'].includes(val('multi_agent')), 'Untrusted dependency or agent joins the execution chain', 'Dynamic components or relationships can introduce new instructions and capabilities without review, provenance or stable security assumptions.', 'high', ['supply-chain', 'multi-agent']);
    add(['none', 'soft'].includes(val('cost_limits')) && ['full', 'limited'].includes(val('autonomy')), 'Runaway loop and denial-of-wallet', 'Autonomous execution without hard resource limits can create unbounded token spend, recursive tool use or sustained service degradation.', 'high', ['resource']);
    return paths;
}
export function evaluateAssessment(answers = {}, context = {}) {
    const responses = [];
    const tagCounts = new Map();
    let exposureTotal = 0, exposureMax = 0, controlTotal = 0, controlMax = 0, evidenceTotal = 0;
    for (const q of questionnaire) {
        const supplied = normaliseAnswer(answers[q.id]);
        const selected = q.options.find(o => o.value === supplied.value);
        if (!selected)
            throw new Error(`Missing or invalid answer: ${q.id}`);
        const ev = EVIDENCE[supplied.evidence] || EVIDENCE.none;
        const adjusted = Math.min(10, selected.points * ev.multiplier);
        if (q.kind === 'exposure') {
            exposureTotal += selected.points;
            exposureMax += 10;
        }
        else {
            controlTotal += adjusted;
            controlMax += 10;
        }
        evidenceTotal += ev.score;
        selected.tags.forEach(tag => tagCounts.set(tag, (tagCounts.get(tag) || 0) + 1));
        responses.push({ id: q.id, domain: q.domain, kind: q.kind, title: q.title, answer: selected.label, rawPoints: selected.points, points: Math.round(adjusted * 10) / 10, severity: severity(adjusted), tags: selected.tags, evidence: supplied.evidence, evidenceLabel: ev.label, evidenceScore: ev.score });
    }
    const inherentRisk = Math.round((exposureTotal / exposureMax) * 100);
    const controlGap = Math.round((controlTotal / controlMax) * 100);
    const evidenceConfidence = Math.round(evidenceTotal / questionnaire.length);
    const uncertaintyPenalty = Math.round((100 - evidenceConfidence) * 0.12);
    const score = Math.min(100, Math.round(inherentRisk * 0.38 + controlGap * 0.62 + uncertaintyPenalty));
    const riskBand = band(score);
    const ranked = [...responses].filter(r => r.points > 0).sort((a, b) => b.points - a.points || a.evidenceScore - b.evidenceScore);
    const findings = ranked.map((r, i) => ({ id: `F-${String(i + 1).padStart(2, '0')}`, title: r.title, domain: r.domain, observed: r.answer, severity: r.severity, points: r.points, evidence: r.evidenceLabel, evidenceScore: r.evidenceScore, tags: r.tags, impact: r.points >= 7 ? 'A realistic attack or failure could produce material business harm.' : 'The weakness reduces defence-in-depth and increases uncertainty.', recommendation: uniq(r.tags.flatMap(t => guidance[t] || []))[0] || 'Document, implement and test an appropriate control.', frameworks: uniq(r.tags.flatMap(t => frameworks[t] || [])) }));
    const recommendations = [];
    for (const [tag, count] of [...tagCounts.entries()].sort((a, b) => b[1] - a[1]))
        for (const text of guidance[tag] || [])
            if (!recommendations.some(r => r.text === text))
                recommendations.push({ tag, priority: tag === 'critical' ? 'Immediate' : count > 1 ? 'High' : 'Standard', text, frameworks: frameworks[tag] || [] });
    const paths = attackPaths(answers);
    const controls = questionnaire.filter(q => q.kind === 'control').map(q => { const r = responses.find(x => x.id === q.id); return { name: q.title, domain: q.domain, status: r.rawPoints === 0 && r.evidenceScore >= 70 ? 'verified' : r.rawPoints <= 3 ? 'partial' : 'action', evidence: r.evidenceLabel }; });
    const hasCriticalAttackPath = paths.some(path => path.severity === 'critical');
    const decision = hasCriticalAttackPath ? 'DO NOT DEPLOY' : score >= 75 ? 'DO NOT DEPLOY' : score >= 50 ? 'DEPLOY ONLY AFTER MATERIAL REMEDIATION' : score >= 25 ? 'PROCEED WITH CONDITIONS' : 'PROCEED WITH MONITORING';
    return { score, riskBand, inherentRisk, controlGap, evidenceConfidence, decision, headline: riskBand === 'Low' ? 'A strong baseline is present, subject to evidence verification.' : riskBand === 'Moderate' ? 'Targeted weaknesses should be closed before broader deployment.' : riskBand === 'High' ? 'Material attack paths or control gaps could lead to unauthorised actions or data loss.' : 'Critical attack paths make the current deployment posture unsafe.', findings, topFindings: findings.slice(0, 3), attackPaths: paths, recommendations, controls, responses, agentType: context.agentType || '', methodology: 'AgentRiskLayer v3 separates inherent exposure, control weakness and evidence confidence. Residual risk combines exposure (38%), control gaps (62%) and an uncertainty penalty when controls are not evidenced. This is a structured self-assessment, not a technical verification or penetration test.', frameworkSummary: { owasp: uniq(findings.flatMap(f => f.frameworks).filter(x => x.startsWith('OWASP'))), nist: uniq(findings.flatMap(f => f.frameworks).filter(x => x.startsWith('NIST'))) }, scoring: { inherentRisk, controlGap, evidenceConfidence, uncertaintyPenalty } };
}
